# Generated by Django 5.2.7 on 2025-10-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workers", "0002_alter_worker_face_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="EPPEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("helmet", models.BooleanField(default=False)),
                ("vest", models.BooleanField(default=False)),
                ("boots", models.BooleanField(default=False)),
                ("is_complete", models.BooleanField(default=False)),
                ("missing_items", models.JSONField(blank=True, default=list)),
                (
                    "warning_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workers.worker"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerEPPStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_warnings", models.IntegerField(default=0)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("Completo", "Completo"),
                            ("Incompleto", "Incompleto"),
                        ],
                        default="Completo",
                        max_length=20,
                    ),
                ),
                ("last_missing_items", models.JSONField(blank=True, default=list)),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="workers.worker"
                    ),
                ),
            ],
        ),
    ]
